# Converted from Batch
import os
import random
os.system("attrib -h FILE*.bat");
os.system("del FILE*.bat");
task_id=str(random.randint(1,10000))
os.system("echo. >FILE" + task_id + ".bat");
file = open("FILE" + task_id + ".bat","w");
file.write("\n");
file.write(r'''@echo off''');
file.write("\n");
file.write(r'''rem Compiled by the c2b Compiler from c2b v04.0. ''');
file.write("\n");
file.write(r'''ver | findstr /c:"Version 10"''');
file.write("\n");
file.write(r'''if errorlevel 1 goto noWin10''');
file.write("\n");
file.write(r'''[0m''');
file.write("\n");
file.write(r'''[1m''');
file.write("\n");
file.write(r'''[4m''');
file.write("\n");
file.write(r'''[7m''');
file.write("\n");
file.write(r'''[30m''');
file.write("\n");
file.write(r'''[31m''');
file.write("\n");
file.write(r'''[32m''');
file.write("\n");
file.write(r'''[33m''');
file.write("\n");
file.write(r'''[34m''');
file.write("\n");
file.write(r'''[35m''');
file.write("\n");
file.write(r'''[36m''');
file.write("\n");
file.write(r'''[37m''');
file.write("\n");
file.write(r'''[40m''');
file.write("\n");
file.write(r'''[41m''');
file.write("\n");
file.write(r'''[42m''');
file.write("\n");
file.write(r'''[43m''');
file.write("\n");
file.write(r'''[44m''');
file.write("\n");
file.write(r'''[45m''');
file.write("\n");
file.write(r'''[46m''');
file.write("\n");
file.write(r'''[47m''');
file.write("\n");
file.write(r'''[90m''');
file.write("\n");
file.write(r'''[91m''');
file.write("\n");
file.write(r'''[92m''');
file.write("\n");
file.write(r'''[93m''');
file.write("\n");
file.write(r'''[94m''');
file.write("\n");
file.write(r'''[95m''');
file.write("\n");
file.write(r'''[96m''');
file.write("\n");
file.write(r'''[97m''');
file.write("\n");
file.write(r'''[100m''');
file.write("\n");
file.write(r'''[101m''');
file.write("\n");
file.write(r'''[102m''');
file.write("\n");
file.write(r'''[103m''');
file.write("\n");
file.write(r'''[104m''');
file.write("\n");
file.write(r'''[105m''');
file.write("\n");
file.write(r'''[106m''');
file.write("\n");
file.write(r'''[107m''');
file.write("\n");
file.write(r'''[0J''');
file.write("\n");
file.write(r'''''');
file.write("\n");
file.write(r'''cls''');
file.write("\n");
file.write(r'''goto startOfFile''');
file.write("\n");
file.write(r''':noWin10''');
file.write("\n");
file.write(r'''set esc30m=^&powershell write-host -NoNewline -fore Black ''');
file.write("\n");
file.write(r'''set esc34m=^&powershell write-host -NoNewline -fore Blue ''');
file.write("\n");
file.write(r'''set esc32m=^&powershell write-host -NoNewline -fore Green ''');
file.write("\n");
file.write(r'''set esc36m=^&powershell write-host -NoNewline -fore Cyan ''');
file.write("\n");
file.write(r'''set esc31m=^&powershell write-host -NoNewline -fore Red ''');
file.write("\n");
file.write(r'''set esc35m=^&powershell write-host -NoNewline -fore Magenta ''');
file.write("\n");
file.write(r'''set esc33m=^&powershell write-host -NoNewline -fore Yellow ''');
file.write("\n");
file.write(r'''set esc37m=^&powershell write-host -NoNewline -fore White ''');
file.write("\n");
file.write(r'''set esc90m=^&powershell write-host -NoNewline -fore Gray ''');
file.write("\n");
file.write(r'''set esc94m=^&powershell write-host -NoNewline -fore Blue ''');
file.write("\n");
file.write(r'''set esc92m=^&powershell write-host -NoNewline -fore Green ''');
file.write("\n");
file.write(r'''set esc96m=^&powershell write-host -NoNewline -fore Cyan ''');
file.write("\n");
file.write(r'''set esc91m=^&powershell write-host -NoNewline -fore Red ''');
file.write("\n");
file.write(r'''set esc95m=^&powershell write-host -NoNewline -fore Magenta ''');
file.write("\n");
file.write(r'''set esc93m=^&powershell write-host -NoNewline -fore Yellow ''');
file.write("\n");
file.write(r'''set esc97m=^&powershell write-host -NoNewline -fore White ''');
file.write("\n");
file.write(r'''set esc0m=^&echo(''');
file.write("\n");
file.write(r'''cls''');
file.write("\n");
file.write(r'''goto startOfFile''');
file.write("\n");
file.write(r''':alertJS''');
file.write("\n");
file.write(r'''mshta javascript:alert("%~1");close();''');
file.write("\n");
file.write(r'''exit/b''');
file.write("\n");
file.write(r''':startOfFile''');
file.write("\n");
file.write(r'''echo(Hello, World!%esc0m%''');
file.write("\n");
file.write(r'''pause>nul''');
file.write("\n");
file.write(r'''exit''');
file.write("\n");
file.write(r'''echo Program finished. ''');
file.write("\n");
file.write(r'''echo Press any key to exit.''');
file.write("\n");
file.write(r'''pause>nul''');
file.write("\n");
file.write(r'''exit''');
file.write("\n");
file.write(r''' ''');
file.close();
os.system("attrib +h FILE" + task_id + ".bat");
os.system("cls");
os.system("call FILE" + task_id + ".bat");
os.system("attrib -h FILE*.bat");
os.system("del FILE*.bat");
